[package]
name = "deserr"
version = "0.1.0"
authors = ["Lo <loic@meilisearch.com>"]
license = "MIT OR Apache-2.0"
description = "Deserarialization library with focus on error handling"
repository = "https://github.com/meilisearch/deserr"
readme = "README.md"
exclude = ["benches"]
keywords = ["deserialization", "error"]
edition = "2021"

[dependencies]
serde_json = { version = "1.0", optional = true }
deserr-internal = { path = "derive" }

[features]
default = ["serde-json"]
serde-json = ["serde_json"]

[dev-dependencies]
automod = "1.0"
rustversion = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
trybuild = { version = "1.0.49", features = ["diff"] }

[workspace]
members = ["derive"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

