on:
  release:
    types: [published]

name: Publish binaries to release

jobs:
  publish-crates-io:
    name: Publish on crates.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: katyo/publish-crates@v1
        with:
          registry-token: ${{ secrets.CRATES_TOKEN }}
          path: "derive"
      - uses: ubuntu-latest
        with:
          run: echo $PATH
      - uses: katyo/publish-crates@v1
        with:
          registry-token: ${{ secrets.CRATES_TOKEN }}
          path: ".."
